# Site settings
title: Luuk Kenselaar
email: mail@LKenselaar.dev
url: https://LKenselaar.dev/
description: "The personal website of Luuk Kenselaar"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: lkenselaar.dev

# Social networks usernames
social:
  - title: twitter
    url: https://twitter.com/lkenselaar
  - title: mastodon
    url: https://mastodon.world/@lkenselaar

# Build settings
markdown: kramdown
permalink: pretty
