# Site settings
title: Luuk Kenselaar
email: mail@LKenselaar.dev
url: https://LKenselaar.dev/
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: lkenselaar.dev

# Social networks usernames
social:
  - title: twitter
    url: https://twitter.com/lkenselaar

# Build settings
markdown: kramdown
permalink: pretty
